typography_spectrum: 0
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#d8d8d8'
    - '#7c7c7c'
    - '#353535'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.66494
analytics:
  google: null
  facebook: null
  twitter: null
name: fixed4cal
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about to see..
    url: 'http://www.fixed4cal.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: fixed4cal
purpose: []
