name: fixedfocal
favicon: null
layout_spectrum: 0.00206
typography_spectrum: 0.02706
title: fixedfocal
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#d8d8d8'
    - '#7c7c7c'
    - '#353535'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
