typography_spectrum: 0.5379442253615707
color:
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  brandStrength: 0.9613018285017461
  lightness: 0.1787816770374775
  saturation: 0.5231364909559488
  rhythmicContrast: 0.12499284744262695
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08360561146400869
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: alex Yi
  email: alex@fixed4cal.com
name: fixed4cal
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about to see..
    url: 'http://www.fixed4cal.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: fixed4cal
description: >-
  Alex Yi is a photographer ,Nikon shooter and Kimchi enthusiast living in
  Melbourne.
purpose: []
