name: fixedfocal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02706
title: fixedfocal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#d8d8d8'
    - '#7c7c7c'
    - '#353535'
  brandStrength: 0
  lightness: 0.4194928528741002
  saturation: 0.26245941151864827
  rhythmicContrast: 0.8872300756629556
purpose: []
